### ISSUE TITLE
Add a Flutter example

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/examples#20]

**Comment by tinahollygb** [comment]
When adding the Flutter example, verify this PR makes sense: https://github.com/growthbook/growthbook/pull/750

**Comment by tinahollygb** [comment]
Also consider these changes: https://github.com/growthbook/growthbook/pull/750

**Comment by princebansal** [comment]
@tinahollygb We kinda missed this and I just saw this is lying stale since Jan 4. We will be addressing this by the coming end of the week for sure. 
Next time, anything related to Flutter SDK, you can tag me or @DK070202 on github or in the slack #flutter channel. 
Thanks
